%This script simply cinvert the probability mask generated by Ilastik into
%binarized images, 1 being putative spindles, 0 being the background.
function [gred,Labelst0,compmovie,ggreen]=spindlemaskold(namefile,Ecadchannel,Jupchannel,Probfolder,Thresholdfactor,resX,resY,nfile,x1,x2,Probsuffix,mode)

gred=zeros(resX,resY,nfile); %adjust to the resolution of images

if (strcmp(mode,'avi'))
%# create AVI object
nFrames = x2-x1+1;
vidObj = VideoWriter('Results\compmovie.avi');
% vidObj.Quality = 100;
vidObj.FrameRate = 15;
open(vidObj);
end

    for Time = x1:x2

    % Reading Data
    %----------------------
        fname=[namefile, num2str(Time-1,'%03d'),'.tif'];
        info=imfinfo(fname);
        red=imread(fname, Jupchannel);
        green=imread(fname,Ecadchannel);
        gred(:,:,Time)=mat2gray(red);
        ggreen(:,:,Time)=mat2gray(green);

        probmask=[Probfolder,namefile, num2str(Time-1,'%03d'),Probsuffix];
        segmask=h5read(probmask, '/exported_data');
        segprob=permute(squeeze(segmask(2,:,:,:)),[2,1]);
        probresized=imresize(segprob, [resX resY]);


    % % Strarting watershed on red channel
    %-----------------------------------------------

        lev=graythresh(probresized);
        b= probresized>=Thresholdfactor*lev;        %The threshold to create Labelst0 wich is important to segment the elipse of spindle
        Labelst0(:,:,Time)=bwlabel(b);
        rLabelst0(:,:,Time)=imresize(Labelst0(:,:,Time)>0,0.5);
        rgred(:,:,Time)=imresize(gred(:,:,Time),0.5);
        regred=rgred(:,:,Time);
        regred(regred<0)=0;
        regred(regred>1)=1;
        compmovie(:,:,Time)=cat(2,rLabelst0(:,:,Time),regred);

    if (strcmp(mode,'avi'))
    writeVideo(vidObj, compmovie(:,:,Time));
    end
    end
   
end
